using System;
using System.Collections.Generic;
using System.Text;

namespace Template.Core.DTOs
{
    public class UserDto
    {
        /// <summary>
        /// Autogenerated Id for user entity
        /// </summary>
        public int Id { get; set; }
        public string Token { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public DateTime CreatedAt { get; set; }

    }
}
